management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:"http://localhost:9411/api/v2/spans"}
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}] '
  level:
    com.keakimleang.configserver: TRACE
    com.github.loki4j: DEBUG

# Eureka Client Configuration
services.uris:
  product-service: ${PRODUCT_SERVICE_URI:http://localhost:8081}
  order-service: ${ORDER_SERVICE_URI:http://localhost:8082}
  inventory-service: ${INVENTORY_SERVICE_URI:http://localhost:8083}


logging.loki.url: ${LOKI_ENDPOINT:http://localhost:3100/loki/api/v1/push}
